### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error при частом запуске client.audio.search

### ISSUE THREAD

**Issue by Ungaminga** [ciricc/easyvk#3]
easyvk 2.2.0

Если запустить пару раз скрипт, который ищет аудио и проходит до конца - приложение падает с 
`UnhandledPromiseRejectionWarning: Error`. При этом, исключение не ловиться через конструкцию then().catch().
```d:\dev\vk_music>node index.js
(node:8420) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabli
ng certificate verification.
loop: 0
0 50
(node:8420) UnhandledPromiseRejectionWarning: Error
    at Request.request.post [as _callback] (d:\dev\vk_music\node_modules\easyvk\src\utils\http.js:263:23)
    at Request.self.callback (d:\dev\vk_music\node_modules\request\request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (d:\dev\vk_music\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (d:\dev\vk_music\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:8420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
t a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code.
```

```
const easyvk = require('easyvk')({
    username: "",
    password: "",
    reauth: true,
})

var vkr_output = [];
var loop = 0;
function read_audio(client, q, offset) {
	client.audio.search({q:q, offset:offset}).then(({vkr}) => {
		console.log('loop:', loop++)
		console.log(offset, vkr.length);
		if (vkr.length == 0 && offset == 0)
		{
			console.log("Nothing found");
			return;
		}
		vkr_output = vkr_output.concat(vkr);
		if (vkr.length < 50){
			console.log(vkr_output.length, vkr_output[vkr_output.length-1])
			return;
		}
		read_audio(client, q, offset+50);
	}).catch((error) => {
      console.log(error,'Promise error');
  });
};

easyvk.then(vk => {
	vk.http.loginByForm().then(({client}) => {
		read_audio(client, 'Jesus and mary chain', 0);
	}).catch((error) => {
      console.log(error,'Promise error');
  });
});
```

**Comment by ciricc** [comment]
Исправляется на dev ветке. Скоро будет фикс.

**Comment by ciricc** [comment]
Для подобных обращений с easyvk@2.2.1 есть метод audio.searchAll('Jesus and mary chain', 1000)

```javascript
const easyvk = require('easyvk')

easyvk({
  password: 'password',
  username: 'username'
}).then(async (vk) => {

  let {client} = await vk.http.loginByForm()
  let count = 1000
  
  return client.audio.searchAll('Jesus and mary chain', count)

}).catch(console.error)
```
